#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

RED="\033[1;31m"
GREEN="\033[1;32m"
NC="\033[0m"

staged_files=$(git diff --cached --name-only)

changelog_exit_code=0
linter_exit_code=0
test_exit_code=0

if ! [ -z "$staged_files" ]
then
  yarn lint
  linter_exit_code=$?
  yarn test
  test_exit_code=$?
fi

if [ $linter_exit_code -ne 0 ]
then
  echo "${RED} ❌ Eslint${NC}"
else
  echo "${GREEN} ✔ Eslint${NC}"
fi

if [ $test_exit_code -ne 0 ]
then
  echo "${RED} ❌ Tests${NC}"
else
  echo "${GREEN} ✔ Tests${NC}"
fi

if [ $(($linter_exit_code + $test_exit_code)) -ne 0 ]
then
  exit 1
fi

exit 0
